### ISSUE TITLE
Ports do not get published

### ISSUE THREAD

**Issue by mbound** [networkop/docker-topo#30]
Hi, 
I am trying to publish ports to the host from one container in my topology, but even though the docker-topo --create script appears to succeed, the port doesn't get published.

Here is the topology I am using:

```
VERSION: 2

CUSTOM_IMAGE:
      onos: onosproject/onos
PUBLISH_BASE:
      8181/tcp: 8383 # publish GUI port to host
#driver: veth
links:
    - endpoints: ["vmx-a1:eth0", "vmx-g1:eth0","vmx-b1:eth0","vmx-g2:eth0","onos:eth0"]
      driver: bridge
```
